blank_issues_enabled: false
contact_links:
  - name: Equicord Support Server
    url: https://discord.gg/equicord-1173279886065029291
    about: If you need help regarding Equibop or Equicord, please join our support server!
