name: Update metainfo on release

on:
    release:
        types:
            - published
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Update metainfo
              run: bun run generateMeta

            - name: Commit and merge in changes
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  gh release upload "${{ github.event.release.tag_name }}" dist/org.equicord.equibop.metainfo.xml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
