name: Upload node_modules to release

on:
    release:
        types:
            - published
    workflow_dispatch:

permissions:
    contents: write

jobs:
    upload:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Create node_modules tarball
              run: tar -czf node_modules.tar.gz node_modules/

            - name: Upload to release
              run: |
                  gh release upload "${{ github.event.release.tag_name }}" node_modules.tar.gz
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
